language: java
services:
  - postgresql
before script:
  - psql -c 'CREATE DATABASE todolist_spark_test;' -U postgres
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  mvn test