language: java
services: postgresql
before_install: psql -c 'CREATE DATABASE todolist_spark_test;' -U postgres
before script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test